### ISSUE TITLE
computeDestinationPoint give slightly incorrect result

### ISSUE THREAD

**Issue by yashgt** [manuelbieh/Geolib#102]
var point = { latitude: 18.5075232, longitude: 73.8047121 }
point = geolib.computeDestinationPoint(point, 5000, 0);

I get:
{ latitude: 18.55243896420598, longitude: 73.80471209999999 }
The bearing being 0, the longitude was expected to remain the same as the original point.  However, it goes slightly off.

**Comment by tdrake-cb** [comment]
I'm curious about this too, I need a more accurate calculation for my application. Can anyone point me to a resource that provides this?

**Comment by manuelbieh** [comment]
Mitigated this a little in the upcoming v3 release: longitude remains the same for a bearing of `0` and `180` as long as the result is not `< -180` or `> 180`.
