### ISSUE TITLE
getBoundsOfDistance method not working.

### ISSUE THREAD

**Issue by avinashgautam92** [manuelbieh/geolib#103]
I tried to call this getBoundsOfDistance method woth two parameter point and distance, Point consist of a geo location i.e longitude and latitude. This method was suppose to give me all coordinates near by point to specified distance. This method always yields error like

 Error: Unknown format.

Please help, how it will work. I don't see any documentation for using this method as well.

**Comment by manuelbieh** [comment]
Method is now documented in v3.0.0 which will be released shortly.
