### ISSUE TITLE
Feature Request: Enhance getDistance

### ISSUE THREAD

**Issue by schang933** [manuelbieh/Geolib#105]
Taking `isPointInsideRobust()` from #47 a step further, would be awesome to enhance `getDistance()` with distance to polygons (`getPolygonDistance()`?), defined below.
- Accepts a latlng and polygon
- Returns the nearest distance from the latlng to a point on the polygon's perimeter
- Positive value if outside polygon
- Negative value if inside polygon

Essentially `isPointInsideRobust()` with distance information. It's a common operation in tools like ArcGIS. Seems the best implementation method I could find was to [compute distance to each line segment](http://gis.stackexchange.com/questions/209699/distance-of-points-to-a-polygon-inside-and-out-without-proximity-toolset-arcg), then negate the result if the point is inside. Unfortunately geolib doesn't have a point-to-line distance either, so atm this doesn't seem possible to do.

**Comment by manuelbieh** [comment]
Hi,

we already have [#getDistanceFromLine](https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L988) - if I got you right you are looking for a similar function getDistanceFromPolygon?

If I got you right we could solve that by iterating through the points of a polygon - two points at a time - and finding the nearest point to any of those lines?!

**Comment by manuelbieh** [comment]
So let's assume our point is `var point = [1.5, 2]` and our polygon (is actually a square) and consists of the following points: 
```
var polygon = [
  [0, 0], 
  [0, 1], 
  [1, 1], 
  [1, 0]
]
```

We would then get the following distances:
```
var distances = [
  geolib.getDistanceFromLine(point, polygon[0], polygon[1]),
  geolib.getDistanceFromLine(point, polygon[1], polygon[2]),
  geolib.getDistanceFromLine(point, polygon[2], polygon[3]),
  geolib.getDistanceFromLine(point, polygon[3], polygon[0])
];
```

which results in:
```
166979
200223
123785
228044
```
So distance to the line between points [[1,1], [1,0]]  is nearest (123785) so `getDistanceFromPolygon` would result in something like:

```
{
  distance: 123785,
  points: [
    [1,1],
    [1,0]
  ]
}

**Comment by schang933** [comment]
Thanks for the quick response @manuelbieh! I didn't know about `getDistanceFromLine()`, maybe consider adding it to the README 😄 

But yes, this is exactly what I was going for. I wasn't sure if there was a more efficient way, but I would have taken the approach you wrote above.

**Comment by manuelbieh** [comment]
`isPointInsideRobust` is just taken from here https://github.com/mikolalysenko/robust-point-in-polygon - so I'm considering to drop it completely. Not sure about that though.
