### ISSUE TITLE
Feature Request: Add option to include the source coords in orderByDistance()

### ISSUE THREAD

**Issue by bkilrain** [manuelbieh/Geolib#107]
I recently used geolib on a project and really could have used this feature on orderByDistance.

**Comment by manuelbieh** [comment]
Just because of interest: what did you need it for?

Not quite sure about it since it adds additional complexity to the library for something that can be done by hand in one line pretty easily:

```
let source = {lat: 51, lng: 7};
let coords = [{lat: 52, lng: 7}, {lat: 51.5, lng: 8}, {lat: 50, lng: 7.5}];

let distances = [Object.assign({}, source, { distance: 0, key: 'source'})].concat(
    geolib.orderByDistance(source, coords)
);
```

**Comment by bkilrain** [comment]
I was ordering geotagged photos in an app that attempted to match similar photos from as far away as possible. My app was meh... but your library was very handy. 

I understand you want to keep things light and nimble. When I ran into this issue, I made a note to send a PR when I had a chance and ended up solving it similarly to how you suggested.

**Comment by manuelbieh** [comment]
This function will be rewritten in the upcoming v3 and will only return an array of ordered points in the future.
