### ISSUE TITLE
Haversine algorithm support

### ISSUE THREAD

**Issue by Gardezi1** [manuelbieh/Geolib#109]
I was wondering that does your package support haversine since I looked into your documentation and I was not able to find any haversine function or anything. I am looking for something like this 

```
distance->in('km')->haversine();
```

**Comment by manuelbieh** [comment]
If I'm not wrong, this here should be the haversine formula for distance calculation: 
https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L341

Is that what you were looking for?
