### ISSUE TITLE
geolib.elevation

### ISSUE THREAD

**Issue by smykes** [manuelbieh/geolib#111]
I have the following code:

`var geolib = require("geolib");`
`var data = [
    {
      "Name": "Sports Authority Field at Mile High",
      "City": "Denver",
      "State": "Colorado",
      "Surface": "Grass",
      "Roof": "Open",
      "Geo" : {
        "Lat": "39.743889",
        "Long": "-105.02"
      }
    }
  ]`
`geolib.elevation({"lat":  data[i].Geo.Lat, "lng": data[i].Geo.Long});`

I am receiving undefined for the returned value whether the coordinates are being passed in as strings or not.  I'm not sure why this is happening, I'm probably missing something obvious.  Any help appreciated.

**Comment by jmanuel1609** [comment]
Any updates for this issue  please.  I am having the same issue.
thanks

**Comment by manuelbieh** [comment]
Elevation support will be (temporarily?) dropped in v3.0.0 which is about to be released, sorry!
