### ISSUE TITLE
Unable to get appropriate result on passing dynamic object with hardcoded array in IsPointInside

### ISSUE THREAD

**Issue by areox24** [manuelbieh/Geolib#112]
var latling = { "latitude": 73.06831, "longitude": 33.6663874 };
  if (isPointInside(
    latling,
    [
      { latitude: 73.06015491485596, longitude: 33.669318391264554 },
      { latitude: 73.07549715042114, longitude: 33.67733633656512 },
      { latitude: 73.08568954467773, longitude: 33.66356786778117 }
    ]
  )

Works

But when 

var lat=Float value from Database;
var long=Float value from Database;
var latling = { "latitude": lat, "longitude":  long};

object is passed,

The result is always false, as if 1st argument was incorrect. But no error is generated in log

Kindly guide me in the right direction

-Platform : Node Js
Npm

**Comment by JacobJT** [comment]
Double check you have the values you think you do when you create that `latling` (also, check your spelling). If you're pulling from a database perhaps you're doing an asynchronous operation and trying to execute before you actually have data?
