### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by vvenegasv** [manuelbieh/Geolib#114]
Hello, nice work. I found this library very helpfull.

I was looking typescript definition, but there isn't, so I made it. Maybe, you could append [this](https://s3.amazonaws.com/personal-vladimir-venegas/types/geolib.d.ts) to this repo.

Thanks a lot and have a nice day :)

PS: Sorry for my bad english

**Comment by manuelbieh** [comment]
Nice. Thanks a lot! Can you maybe create a pull request for that?

**Comment by vvenegasv** [comment]
Sure, but i will need access to do it. Or not?

**Comment by manuelbieh** [comment]
Just click "fork" (top right corner), clone your fork (`git clone git@github.com:vvenegasv/Geolib.git`), add the file, `git commit`, `git push`, then go back to github and click "Create Pull Request" 😉

**Comment by mightyiam** [comment]
Seems like this issue can be closed. `master` branch seems to contain the `d.ts` file and `package.json` seems to contain the `typings` field.

Could you please release?

**Comment by vvenegasv** [comment]
yes i will close, my bad ;)

**Comment by mightyiam** [comment]
Just to make sure it is clear, what I meant by "release" is to ask the maintainer to publish a new version.

**Comment by vvenegasv** [comment]
Excuseme, i am not an expert on best practices using github. As far as I know, this issue was released in this pull request https://github.com/manuelbieh/Geolib/pull/115 and it will target to master branch.

**Comment by manuelbieh** [comment]
Should have been published long ago. Please reopen if not 😉
