### ISSUE TITLE
What model of the Earth is this using?

### ISSUE THREAD

**Issue by mraak** [manuelbieh/Geolib#116]
Flat, spherical, elliptical (WGS84)?

**Comment by Shivang44** [comment]
I don't know much about geography or really any of this stuff haha, but using this page:

http://www.movable-type.co.uk/scripts/latlong.html

I found the distance between my two coordinates to be 1646 meters, which is exactly what geolib returned. And that page says:

> All these formulæ are for calculations on the basis of a spherical earth (ignoring ellipsoidal effects) – which is accurate enough* for most purposes… [In fact, the earth is very slightly ellipsoidal; using a spherical model gives errors typically up to 0.3%1 – see notes for further details].

So... I will say based on a spherical model. Please correct me if I'm wrong!

**Comment by manuelbieh** [comment]
WGS84 / Mercator
