### ISSUE TITLE
getCenter should return latitude and longitude as float

### ISSUE THREAD

**Issue by Fed29** [manuelbieh/Geolib#117]
Missing parseFloat at https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L461

Is there any reason for truncate precision at 6 digits?

**Comment by henrinormak** [comment]
At least the type should be fixed, currently the type of getCenter suggests that it returns a set of floats.

**Comment by manuelbieh** [comment]
That's clearly a bug. I will fix this. I have no idea what I thought when I implemented that back in the days 🤦‍♂️

**Comment by manuelbieh** [comment]
Will be fixed in v3 which I will release shortly.
