### ISSUE TITLE
Get bounds from center within X distance radius

### ISSUE THREAD

**Issue by Noitidart** [manuelbieh/Geolib#122]
Hi there,
Thanks for such an excellent module! I am trying to get the max bounds for X miles around a `lat1, lng1`. I couldn't find a function in this lib to do this. Is this correct?

**Comment by ramsestom** [comment]
use getBoundsOfDistance(point, distance). You have to convert your miles distance to meters before using it though...

**Comment by Noitidart** [comment]
Thank you @ramsestom !
