### ISSUE TITLE
Type definitions missing short lat/lng format

### ISSUE THREAD

**Issue by mightyiam** [manuelbieh/Geolib#124]

**Comment by manuelbieh** [comment]
I'm not exactly sure what you mean tbh 😄

**Comment by mightyiam** [comment]
[These](https://github.com/manuelbieh/Geolib/blob/24b1ac5576e7f8e891b7dd59fa809c21ef4ae4b9/dist/geolib.d.ts#L8-L16) are not complete, right? Because the library accepts the short format `lat/lng` properties, right?

**Comment by manuelbieh** [comment]
Ahhh, now I know what you're talking about 😄. Yes, they seem to be incomplete. Feel free to add the missing definitions. I have never created a typescript definition file before so I have no idea how to mark them as optional/additional 😉

**Comment by manuelbieh** [comment]
This will be fixed in the upcoming v3 release, which is completely written in TypeScript
