### ISSUE TITLE
isPointInCircle not correct

### ISSUE THREAD

**Issue by mohamedtijani** [manuelbieh/Geolib#131]
Here is the result of my treatment
https://us-central1-yusalak-9fc53.cloudfunctions.net/getNearByShops?lat=23.582024&lng=58.394815

code:

`var lat = request.query.lat;
    var lng = request.query.lng;
    var shops = [];

  var checkPoint = { latitude: lat, longitude: lng }
  var centerPoint = { latitude: shop.locations.center.lat, longitude: shop.locations.center.lng };

_.mapKeys(shopList, (shop, i) => {
 shops.push({
                     id: i,
                    radius: shop.locations.radius,
                    canterLat: lat,
                    centerLng: lng,
                    pointCheckLat: shop.locations.center.lat,
                    pointCheckLng: shop.locations.center.lng,
                    isPointInCircle: geolib.isPointInCircle(checkPoint, centerPoint, shop.locations.radius)
                });
  });

response.setHeader('Content-Type', 'application/json');
response.send(JSON.stringify(shops));
`

**Comment by manuelbieh** [comment]
```
geolib.getDistance(
  { lat: 23.582024, lng: 58.394815 },
  { lat: 23.536291093876567, lng: 58.44451904296875}
);
```
> 7170

So you're checking if your coordinates A are within a 300 meters radius of coordinates B. The distance between these 2 coordinates are 7170 meters so the result `false` is correct.

**Comment by mohamedtijani** [comment]
in my system 300km 
the problem is solved

`isPointInCircle: geolib.isPointInCircle(checkPoint, centerPoint, shop.locations.radius*1000)`

Thank you
