### ISSUE TITLE
getting different result for getPathLength

### ISSUE THREAD

**Issue by themaincharacter** [manuelbieh/Geolib#132]
I'm trying to understand why I'm getting a different result doing the exact same path calculation
for getPathLength as stated in the docs.

geolib.getPathLength([
    {latitude: 52.516272, longitude: 13.377722}, // Berlin
    {latitude: 51.515, longitude: 7.453619}, // Dortmund
    {latitude: 51.503333, longitude: -0.119722} // London
]);

Heres what I'm doing:
console.log(geolib.getPathLength([
                    {latitude: 52.516272, longitude: 13.377722}, // Berlin
                    {latitude: 51.515, longitude: 7.453619}, // Dortmund
                    {latitude: 51.503333, longitude: -0.119722} // London
                ]));

this results in 947117 instead of the expected 945235. What am I doing wrong here? I'm using the latest build.

**Comment by gggauravgandhi** [comment]
Using what you are getting expected ** 945235**?

**Comment by manuelbieh** [comment]
Docs seem to be outdated here. I switched from using `getDistanceSimple` to `getDistance` at some point in the past. It's a slower but more accurate calculation.
