### ISSUE TITLE
OrderByDistance attempted to assign to readonly property

### ISSUE THREAD

**Issue by adrianha** [manuelbieh/Geolib#134]
Hi,
Sometimes i got an error when using geolib.findNearest because its `attempted to assign to readonly property`.
After i look at the code its raised because of this (Line: 950 on dist version):
https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L937-L939

Could we change to:
```
var augmentedCoord = {
  key: idx,
  distance: distance
};
```

Thanks

**Comment by manuelbieh** [comment]
This behavior is changed/fixed in v3 which I will release shortly!
