### ISSUE TITLE
How to include this library in react-native project

### ISSUE THREAD

**Issue by anjali14garg** [manuelbieh/Geolib#139]
i have installed this library using the npm command you have given. But how to import it into the class.

**Comment by manuelbieh** [comment]
Well, it should actually be as simple as `import geolib from 'geolib'` - i haven't worked with react-native yet but it should work fine, i guess

**Comment by jack2684** [comment]
This maybe a super noob question. But still better if we can document the following line in README.md. 😅 
```
import geolib from 'geolib'
```

Thx for answer tho, it works great!!
