### ISSUE TITLE
Select locations in radius from given location

### ISSUE THREAD

**Issue by rabet** [manuelbieh/Geolib#142]
Hey,

thanks for this great library! I need to select from my DB entries which have lat and lng in a radius (given in metres) from the basic lat, lng object. Is that somehow possible with Geolib?

I was thinking to use getDistance method, but it needs to lookup through every entry's lat-lng data, get the distance from the basic point and return true or false which seems to be very expensive to me.

Thanks for any direction :)

**Comment by manuelbieh** [comment]
You can use `geolib.withinRadius` and Array.filter for that.
```
const coordsWithinRadius = ArrayOfCoords.filter((coord) => geolib.withinRadius(coord, origin, radius);
```
