### ISSUE TITLE
Which Geolib?

### ISSUE THREAD

**Issue by DaveInCaz** [manuelbieh/Geolib#147]
Is this project the same as http://www.geolib.co.uk/index.htm ?

Thanks

**Comment by manuelbieh** [comment]
No. Completely different project and in no way affiliated.

**Comment by DaveInCaz** [comment]
Thanks for clarifying. That is unfortunately confusing. The other project has been around for a while, maybe you should alter the name of the project here. (Note - I'm unaffiliated with the other Geolib). Best regards

**Comment by manuelbieh** [comment]
Would be interesting to know who was first ;)
First commit (v1.17.0) was pushed to github on 22 Sep 2011
https://github.com/manuelbieh/Geolib/tree/7bc6b314fbc7daf22cd59378b1a5b0566f7b9985
before that it was hosted on Google Code. 

That other Geolib tool says _© Copyright GeoLib 2012_ - would be interesting to know if that is the date they released it initially or the date they released the most recent version :wink:

**Comment by DaveInCaz** [comment]
I don't know the authoritative answer but their documentation page has a date in 2008: http://www.geolib.co.uk/doxygen/hierarchy.html
