### ISSUE TITLE
Can show distance same as Google Map ?

### ISSUE THREAD

**Issue by MinhNQ90** [manuelbieh/Geolib#149]
Hi,
I use your library in React Native. It work well but your result return distance between 2 points look like doesn't same as google map. I think GG Map distance is the road distance but your are not.
So in your library is there any method can return the road distance as GG Map ? Thank you.

**Comment by chris1705** [comment]
The geolib library calculates the linear distance between two geocoordinates and not the route between two places as Google Maps.
