### ISSUE TITLE
Refine `findNearest` type declaration

### ISSUE THREAD

**Issue by musou1500** [manuelbieh/Geolib#152]
I think
* `Distance` should be added to return type 
* `coords` should accepts `{ [key: string]: PositionAsDecimal }`

here is a new declaration.

```typescript
function findNearest(
  latlng: PositionAsDecimal,
  coords: PositionAsDecimal[] | { [key: string]: PositionAsDecimal },
  offset?: number,
  limit?: number
): Distance[] | Distance;
```

I can send PR, but please help me if you have a better idea.

**Comment by rodrigoords** [comment]
Any news ?

**Comment by manuelbieh** [comment]
This is fixed in v3, which is completely written in TypeScript and will be released shortly.
