### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by snyypi** [manuelbieh/Geolib#154]
Hi, I came across an error, incorrect behavior when rounding using geolib.convertUnit (string unit, float distance [, int round]).

In some cases, there remains a residue.
For example:
instead of geolib.convertUnit ('km', 14213, 2) // -> 14.21
it turns out geolib.convertUnit ('km', 14213, 2) // -> 14,210000001

Also, in some cases, there may be an inaccuracy in rounding.
Errors are associated with using Math.round.

A simple example showing incorrect behavior leading to rounding errors:
This Math.round (1.005 * 100) / 100 construct will return a value of 1 instead of 1.01.

**Comment by manuelbieh** [comment]
That's an annoying problem in JavaScript (and other languages) with floating point precision:
https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript

**Comment by snyypi** [comment]
Yes, I know about this behavior. It's just that when you look at the documentation (https://github.com/manuelbieh/Geolib#geolibconvertunitstring-unit-float-distance-int-round), you find a method that rounds to the specified value, but it does not return the value you expect, it causes confusion.

And in principle then there is no sense in this parameter if all the same after that it is necessary to do normal rounding.
