### ISSUE TITLE
decimal2sexagesimal should allow me to specify number of decimal places

### ISSUE THREAD

**Issue by samherrmann** [manuelbieh/Geolib#158]
Currently the returned value from the `decimal2sexagesimal` function is opinionated to [2 decimal places](https://github.com/manuelbieh/Geolib/blob/v2.0.22/src/geolib.js#L1265). The desired functionality is to optionally specify the number of decimal places.

Ex:
* `geolib.decimal2sexagesimal(51.49611111); // -> 51° 29' 46.00` 
(keep default behavior as is, 2 decimal places)
* `geolib.decimal2sexagesimal(51.49611111, 3); // -> 51° 29' 46.000`

**Comment by manuelbieh** [comment]
This is changed in v3 which I will release shortly. It will return up to 4 decimal places and is always as long as it needs to be. So in your example the return value should always be `51° 29' 46` and support up to decimal places like `51° 29' 46.0001`. This is micrometer accuracy and should be enough for very most use cases expect you're working for NASA or the military.
