### ISSUE TITLE
orderByDistance returns object with different keys

### ISSUE THREAD

**Issue by ifvictr** [manuelbieh/Geolib#159]
Instead of returning exactly what was inputted, orderByDistance returns an object with the keys `latitude`, `longitude`, `key`, and `distance`. Is this intentional? I also noticed an older issue created for this issue: https://github.com/manuelbieh/Geolib/issues/74

**Comment by manuelbieh** [comment]
This function is completely rewritten and works in a different way in v3 which I will release shortly.
