### ISSUE TITLE
Typescript types missing for GeoJSON inputs

### ISSUE THREAD

**Issue by mklopets** [manuelbieh/Geolib#162]
The [GeoJSON support](https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L87) is not reflected in the TypeScript types – for example, `getBounds` actually seems to support the GeoJSON input format of `[number, number][]` but the TS declarations require a `PositionWithElevation[]` instead.

**Comment by manuelbieh** [comment]
This should be fixed in v3 which I will release shortly.
