### ISSUE TITLE
How to get southwest corner and northeast corner?

### ISSUE THREAD

**Issue by ccoeder** [manuelbieh/Geolib#170]
Hi,

I'm using `getBounds` function to get bounds from an array. But i need southwest corner and northeast corner coordinates. How can i create corners with this result. Which one is southwest or northeast?

`{maxLat: 51.50998, minLat: 51.5099783, maxLng: -0.1325, minLng: -0.1329}`

Thank you.

**Comment by manuelbieh** [comment]
It's currently not possible because it is not taking into account on which hemisphere your coordinates are. Good point, I will have a look at it.

**Comment by ccoeder** [comment]
Thank you for answering my question. 

Is there a date for v3?
Can I help you with this for making fastly?

**Comment by manuelbieh** [comment]
There is no due date for v3 yet as I currently have no project where I'm using Geolib myself so I am only doing it in my free time but if you want to implement a method for v2 and I will port it over to v3 then 🙂

**Comment by ccoeder** [comment]
I will try my best, thank you again 😃
