### ISSUE TITLE
can't compile ts file in project

### ISSUE THREAD

**Issue by livnekes** [manuelbieh/geolib#191]
node_modules/geolib/es/types.d.ts(4,96): error TS8020: JSDoc types can only be used inside documentation comments.

export declare type GeolibGeoJSONPoint = [GeolibLongitudeInputValue, GeolibLatitudeInputValue, **GeolibAltitudeInputValue**?];

**Comment by manuelbieh** [comment]
Oh, weird. Which TypeScript version are you using? Can you describe a bit more what exactly you're doing? Which files you are importing, which functions you are using, etc.?

**Comment by livnekes** [comment]
"typescript": "^2.7.2"

**Comment by livnekes** [comment]
Im only using getDistance for it

**Comment by livnekes** [comment]
after changing to the latest typescript the error was fixed. 
Thanks!

**Comment by livnekes** [comment]
Do u want me to close the issue?
