### ISSUE TITLE
2.0.25 and 2.0.26 introduced breaking regression

### ISSUE THREAD

**Issue by blackdynamo** [manuelbieh/geolib#192]
Hey guys,

Not sure what changed as I am on vacation, but looks like the last 2 patch changes introduced breaking changes. useDecimal is no longer a function.

```
TypeError: geolib.useDecimal is not a function
```

**Comment by manuelbieh** [comment]
Oh shit, it was published by accident and I can't unpublish it anymore. At least npm says _You can no longer unpublish this version. Please deprecate it instead_.

I have just contacted npm support to unpublish it for me. As a workaround you can (suggested) either [upgrade to 3.0.0](https://github.com/manuelbieh/geolib/blob/master/CHANGELOG.md#breaking-changes-in-300-and-migration-from-2xx) which requires some work (probably an afternoon or more) or as a temporary workaround pin the version to 2.0.24 by replacing `"geolib": "^2.0.0"` in your package.json with `"geolib": "2.0.24"`.

**Comment by mhnestler** [comment]
I think it would help to publish a new patch version (2.0.27) restoring the code to what it was in 2.0.24, to stop breakage for everyone installing with `^2.0.0` or similar.

**Comment by manuelbieh** [comment]
Yes. That would be an alternative but I'd like to avoid that because that gives the impression that there was anything new/fixed/patched, which was not. I'll wait for 24 hours for npm to respond and (hopefully) unpublish the package or otherwise I will publish it as 2.0.27.

**Comment by manuelbieh** [comment]
> Support (npm)
> May 29, 05:21 PDT
> Thanks for confirming. I've unpublished geolib@2.0.26. Please let us know if there is anything else we can do for you. We’ll be here to help.

2.0.26 is unpublished. Sorry for the hassle!

**Comment by blackdynamo** [comment]
Thanks. I fixed the version to 2.0.24 for the time being until we have time to upgrade to ^3.0.0
