### ISSUE TITLE
Is there any method to find distance between two locations?

### ISSUE THREAD

**Issue by chanduthedev** [manuelbieh/geolib#200]
Hi Team,

Thanks for the nice library. It helps a lot for me. 
I have query here, is there any function to find the distance between two location points? I can see  **isPointWithinRadius** method which says whether the location is with in a range or not. But not exact distance. Please help me on this.

Thanks again.

**Comment by ddave09** [comment]
It’s in the ReadMe. getDistance()

On Mon, Jun 10, 2019 at 5:52 AM chanduthedev <notifications@github.com>
wrote:

> Hi Team,
>
> Thanks for the nice library. It helps a lot for me.
> I have query here, is there any function to find the distance between two
> location points? I can see *isPointWithinRadius* method which says
> whether the location is with in a range or not. But not exact distance.
> Please help me on this.
>
> Thanks again.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_manuelbieh_geolib_issues_200-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABKZDCMUF7ZZKX6LLZ5KCYDPZYP4TA5CNFSM4HWSBBDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYQ22TA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=wAQdcsGd2s45jX6-nMW5nQ&m=kwSbIDQsAvAzx9a4UIUBwA6yN1owefk12LIF_emajGE&s=pkjVut6TF5K3z0Rze_XoBwpMx9R_w9x1UzrIXVDt4Q0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABKZDCOCTFVFS56TW7QPTP3PZYP4TANCNFSM4HWSBBDA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=wAQdcsGd2s45jX6-nMW5nQ&m=kwSbIDQsAvAzx9a4UIUBwA6yN1owefk12LIF_emajGE&s=7Tl5wCt4UyLiPAnD89p-Q1-XrkNLuaGNjwt6veaOZxY&e=>
> .
>
-- 
Thanks,
Darshit Dave
dd1691@nyu.edu
(646)241-2874

**Comment by chanduthedev** [comment]
Hi @ddave09 ,
Thanks for the quick response. that is  the method I am looking for. I don't know why I missed that method from the read me file ;-). 
Thanks again.
