### ISSUE TITLE
[ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by missinglink** [manuelbieh/geolib#208]
Hi,

Apologies in advance if this is a node issue and not a `geolib` issue, I'm not familiar with this error message.

Up to and including node `v12.10.0` we have had no issue loading this library using the syntax:
```javascript
const geolib = require('geolib');
```

since nodejs version `v12.11.0` we are getting the following error:

```bash
internal/modules/cjs/loader.js:958
      throw new ERR_REQUIRE_ESM(filename);
      ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/travis/build/pelias/api/node_modules/geolib/lib/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:958:13)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/travis/build/pelias/api/controller/placeholder.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
```

**Comment by manuelbieh** [comment]
Oh that's an interesting one. Will check that.

**Comment by rapomon** [comment]
I have the same issue.

**Comment by rapomon** [comment]
I just test it with node 12.11.1 and works fine. It was a problem with node 12.11.0:
This release fixes a regression that prevented from building Node.js using the official source tarball (Richard Lau)
https://nodejs.org/en/blog/release/v12.11.1/

**Comment by pandres95** [comment]
#209 solved the issue for me

**Comment by Niklv** [comment]
Have similar issue on node 13.
```
08:49:12.610 error: (node:6) Warning: require() of ES modules is not supported.
require() of /app/node_modules/geolib/lib/index.js from /app/src/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/geolib/package.json.
```

**Comment by missinglink** [comment]
Heya OP here, the orignially reported issue was resolved in `v12.11.1`, sorry I should have closed it before that last comment came through...

**Comment by rapomon** [comment]
The same here, tested with node 13.1.0:
```
(node:10520) Warning: require() of ES modules is not supported.
require() of C:\nodejs\ebm-one\node_modules\geolib\lib\index.js from C:\nodejs\ebm-one\services\activities.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\nodejs\ebm-one\node_modules\geolib\package.json.
```

**Comment by ptboyer** [comment]
Quite blocked by this one on Node `v12.11.0`.
Seems like `"type": "module"` is just causing a hassle...

**Comment by missinglink** [comment]
@ptboyer did you read the thread above? this is a known issue with `v12.11.0` which was resolved in `v12.11.1`

**Comment by manuelbieh** [comment]
Yeah. Try upgrading your Node to v12.11.0. That should fix it!

**Comment by ptboyer** [comment]
@missinglink @manuelbieh Ah sorry lads! I read it wrong.
Upgraded to `v12.11.1` fixed it. Cheers!

**Comment by rapomon** [comment]
Anyway the problem in node 13 is still there, I have solved it by renaming `geolib/lib/index.js` to `geolib/lib/index.cjs` and changing the reference `{"main": "lib/index.cjs"}` in package.json

**Comment by jamiesteven** [comment]
> Anyway the problem in node 13 is still there

Indeed. I have the same issue in the Node.js current release: 13.2.0.

**Comment by Asner** [comment]
Same issue with Node.js release: 12.13.1 (LTS)

https://github.com/nodejs/node/pull/29909

**Comment by Jeremy38100** [comment]
Same issue.

Please note https://www.npmjs.com/package/geolib has common features and there is no issue.

**Comment by manuelbieh** [comment]
Can we try to consolidate which versions of Node are affected here? 

**Working:**
- 12.11.1

**Broken:**
- 12.11.0
- 12.13.1
- 13.2.0

**Comment by manuelbieh** [comment]
That looks really broken … 12.11.0 does not work, 12.11.1 and 12.12.0 do, 12.13.1 is broken again.

**Comment by arsonik** [comment]
broken in node 13.3.0

**Comment by manuelbieh** [comment]
I just published 3.2.0. Can anyone of you please test it in your environment and tell me if it's fixed? All I did was to remove the `"type": "module"` flag in `package.json`.

**Comment by rapomon** [comment]
Tested with Node 13.1.0 successfully.

**Comment by manuelbieh** [comment]
Happy to hear that! 🙂

**Comment by Asner** [comment]
Tested with Node 12.13.1 (LTS) successfully. Thanks!

**Comment by manuelbieh** [comment]
Alright, thanks. I think this can be considered done then. I'm currently investigating how this whole new ES Module loading mechanism in Node and modern browsers works (or not works). I have a rough high level idea but really not more than that. If you wanna follow me, I'm documenting everything here:
https://github.com/manuelbieh/authoring-modules-in-node

**Comment by rapomon** [comment]
I'm using the last version 3.2.0 of this module with Node Express and a React app, and works fine. Thanks!

**Comment by Mayank-jain34** [comment]
Looks like the same issue got introduced in 12.16.0.

**Comment by DarkLite1** [comment]
We're running node `v13.6.0` with the follwoing `gulpfile.js`:
```javascript
import { src, dest, series, parallel, watch } from 'gulp'
import nodemon from 'gulp-nodemon' // normal nodemon does not display an error on app crash
import env from 'gulp-env'
import browser from 'browser-sync'
import sass from 'gulp-sass'
// Tasks
export default {
    cssTranspile: cssTranspile,
    jsTranspile: jsTranspile,
    server: series(startNodemon, startBrowserSync),
    default: series(
        parallel(
            cssTranspile,
            jsTranspile
        ),
        startNodemon,
        startBrowserSync,
        function () {
            watch('public/scss/*.scss', cssTranspile)
        }
    )
}
```

The error reported is:
```
internal/modules/cjs/loader.js:1160
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: T:\Node\ICP\gulpfile.js
require() of ES modules is not supported.
```
I must be doing something wrong as this seems to be fixed for others. Anyone an idea on what it might be?

**Comment by manuelbieh** [comment]
> The flag "type": "module", is set in package.json as described in the note docs.

It is no longer in 3.2.0. Upgrade your dependency please, that might fix your issue.

**Comment by DarkLite1** [comment]
Thank you for the feedback @manuelbieh but they are the latest and greatest. See [docs here](https://nodejs.org/api/esm.html#esm_package_json_type_field) for the flag.

**Comment by manuelbieh** [comment]
I mean upgrade your geolib dependency to 3.2.x. The `"type": "module"` flag has been removed from `3.1.x` -> `3.2.x`

**Comment by DarkLite1** [comment]
As I don't have the `geolib` package as dependency I guess I should open an issue with `gulp`. I'm sorry, I probably came to the wrong page.

**Comment by scottAhyslop** [comment]
This worked for me:
//I kept getting an ES6 script error when running through Postman, haven't solved, moving on
import { MongoClient } from 'mongodb';
         ^^^^^^^^^^^
SyntaxError: The requested module 'mongodb' does not provide an export named 'MongoClient'
Solution:
//change your start in package.json
"start": "npx nodemon --exec npx babel-node --experimental-modules src/server.js",

//this version of Node works with ES6 extensions, others do not
npm install node@12.11.1

npm i esm // install ES6 bridging lib

node -r esm server.js //from file dir

**Comment by armanrozika** [comment]
I think this is a node issue, I can't even run npx create-react-app.

I am using node 12.16.2.
It's fine in 12.11.1

**Comment by aicayzer** [comment]
@armanrozika is this something which has happened in the last few hours?

I can't run `npx create-react-app` either right now despite being able to do it this morning

**Comment by SrivastavaSrijan** [comment]
Me neither, I cant run npx create-react-app

**Comment by armanrozika** [comment]
@aicayzer Yup, It happened like an hour ago, it is not working suddenly

**Comment by rvempati** [comment]
I am not able to run npx create-react-app hello-world 

It says below error

Must use import to load ES Module: /usr/local/lib/node_modules/create-react-app/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/create-react-app/node_modules/is-promise/index.js from /usr/local/lib/node_modules/create-react-app/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /usr/local/lib/node_modules/create-react-app/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/create-react-app/node_modules/is-promise/package.json.

I am using node 12.16.2 which I downloaded today

**Comment by umakanth-pendyala** [comment]
same issue here guys...but it worked for me earlier...

**Comment by benjaminathlan** [comment]
Same here node `v12.16.0`

**Comment by ghondar** [comment]
same issue here

**Comment by SrivastavaSrijan** [comment]
Try uninstalling your present NodeJS version and installing
https://nodejs.org/download/release/v12.12.0/node-v12.12.0-x64.msi
Worked for me!

**Comment by aicayzer** [comment]
checkout this issue for more help https://github.com/facebook/create-react-app/issues/8896

**Comment by YukaLangbuana** [comment]
Try downgrading Node. This works for me (https://github.com/facebook/create-react-app/issues/8896#issuecomment-619412921)

**Comment by armanrozika** [comment]
It's working now guys, they have fixed it, I tested it in v12.16.2

this is the link to the issue: https://github.com/then/is-promise/pull/15

**Comment by joao-lim4** [comment]
I have this problem in json-serve
This error happens when I leave the
 var lodash = require ('lodash');
var isPromise = require ('is-promise');
main.js file with require syntax

`C:\Users\cl4sh\OneDrive\Área de Trabalho\meat-app-starter-master>json-server db.json
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\node_modules\is-promise\index.js
require() of ES modules is not supported.
require() of C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\node_modules\is-promise\index.js from C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\node_modules\lowdb\lib\main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\node_modules\is-promise\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\node_modules\lowdb\lib\main.js:4:17)    
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'ERR_REQUIRE_ESM'
}`

when I change the require to import this error disappears and this other error enters.
`C:\Users\cl4sh\OneDrive\Área de Trabalho\meat-app-starter-master>json-server db.json

  \{^_^}/ hi!

  Loading db.json
TypeError: lodash.runInContext is not a function
    at module.exports (C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\node_modules\lowdb\lib\main.js:12:18)
    at C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:45:15
    at new Promise (<anonymous>)
    at module.exports (C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:36:10)
    at start (C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:112:12)
    at module.exports (C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:149:3)
    at module.exports (C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\lib\cli\index.js:86:3)
    at Object.<anonymous> (C:\Users\cl4sh\AppData\Roaming\npm\node_modules\json-server\lib\cli\bin.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)`

I've tried everything and nothing resolves ...

**Comment by balakrishna-dev** [comment]
> Heya OP here, the originally reported issue was resolved in `v12.11.1`, sorry I should have closed it before that last comment came through...

it works for me thank you

**Comment by rvempati** [comment]
just tried reinstalling create-react-app and it resolved the issue with create-react-app on node version 12.16.2

**Comment by NayanGitHub** [comment]
Well, the best solution is to rename the index.js to index.cjs and change the reference in package.json to   "main": "index.cjs",

**Comment by benjaminathlan** [comment]
Fixed for me on node `v14.0.0`

**Comment by glud123** [comment]
Downgrade @babel/runtime to 7.7.2 fixed it for me.
https://github.com/standard-things/esm/issues/868#issuecomment-587151825

**Comment by ranjithkumar8352** [comment]
Upgrading geolib from `3.0.x` to `3.2.x` fixed it for me.

**Comment by spikethea** [comment]
Im currently having this problem, but with a simple express server and three.js. My version of node is 12.16.3 LTS. Does anyone else still have the "Must use import to load ES Module" Error?

**Comment by spikethea** [comment]
> Im currently having this problem, but with a simple express server and three.js. My version of node is 12.16.3 LTS. Does anyone else still have the "Must use import to load ES Module" Error?

Aha! Newbie mistake. Of course my node LTS version only includses nodejs as a experimental module. This thread helped me figure that out anyway . Thanks.

**Comment by mathiasfc** [comment]
> Anyway the problem in node 13 is still there, I have solved it by renaming `geolib/lib/index.js` to `geolib/lib/index.cjs` and changing the reference `{"main": "lib/index.cjs"}` in package.json

after some time researching, it was the solution for me, thanks!

**Comment by imdoingotherthings** [comment]
Still broken in v14.4.0. I will try the solution above and check if it works for this version of node.

**Comment by HP4k1h5** [comment]
hi, im following this thread as a sanity check. is it just me or is every last aspect of the ecosystem in some way broken or off these days? no matter which import/require, fs/os/path/__dirname you try, it's bound to crash every other build tool/transpiler you have. ive seen 10 blogs about getting around __dirname when that's not available. there's threads like this everywhere. 

is node just a pile of trash at this point with 8 different footguns for the most basic i/o?

**Comment by asifalikhokhar** [comment]
> I just published 3.2.0. Can anyone of you please test it in your environment and tell me if it's fixed? All I did was to remove the `"type": "module"` flag in `package.json`.

this fixed the issue for me with node v15.1.0

**Comment by nikita-fuchs** [comment]
no success on various node versions , removing `"type": "module"` didn't do anything.

**Comment by fadhlaouir** [comment]
the same problem with `v12.16.1`

**Comment by Sharqiewicz** [comment]
When removing "type": "module" from package.json, 

import _ from "lodash";
^^^^^^

SyntaxError: Cannot use import statement outside a module

appears.

**Comment by mokkenlab** [comment]
same problem win7 node 13.6.0

**Comment by AmeerAsif777** [comment]
Yeah... some problem with v12.16.1 ubuntu

**Comment by kibi0620** [comment]
same problem occurs with node version v14.16.0

**Comment by Teemu11** [comment]
Same with Node v15.10.0

**Comment by nadralia** [comment]
Getting the same on Node v15.13.0

**Comment by KennStack01** [comment]
Node v14.16.1 same problem.

**Comment by JefersonMx** [comment]
Same for me Node v14.15.0

**Comment by NagaPrasath09** [comment]
I have a same issue like this
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Prasath\swagger-api\node_modules\swagger-jsdoc\index.js
require() of ES modules is not supported.

**Comment by abijotgupta** [comment]
I'm using Node.js v14.16.1 and getting this error. I tried everything as described below to remove this issue but still error is there. Help from you is highly appreciated. 

internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/Desktop/Node js project/COINDEX-CLI/node_modules/configstore/index.js
require() of ES modules is not supported.
require() of /Users/Desktop/Node js project/COINDEX-CLI/node_modules/configstore/index.js from /Users/Desktop/Node js project/COINDEX-CLI/lib/KeyManager.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead **rename index.js to end in .cjs**, **change the requiring code to use import()**, or **remove "type": "module"** from /Users/Desktop/Node js project/COINDEX-CLI/node_modules/configstore/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Desktop/Node js project/COINDEX-CLI/lib/KeyManager.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by shayan09** [comment]
Fixed it for me after upgrading node `12.16.3` -> `14.17.0`

**Comment by abijotgupta** [comment]
thank you😊

**Comment by JavaJamie** [comment]
I'm getting this as well when I do a `next build` (node 15.0.1). Any updates?

**Comment by PhilippAubert** [comment]
I have the exact same problem. Using Node 16.3.0

**Comment by tornion** [comment]
same problem. Using node v16.5.0

**Comment by Rohit2010** [comment]
same problem with node version 14.17.5
plz help
![error](https://user-images.githubusercontent.com/59710890/135315116-3889e6dc-48a3-4cab-a38a-079fbc15cf1e.PNG)

**Comment by floriandonod** [comment]
same problem, any updates ?

**Comment by arikumar** [comment]
I am using v18.5.0 still getting same issue.

**Comment by Kurtyjlee** [comment]
Using node 21.5.0, same issue for me :((
