### ISSUE TITLE
check if point inside multi polygons

### ISSUE THREAD

**Issue by AnthonyMouallem** [manuelbieh/geolib#210]
Is it possible to check if point inside one of polygons array instead of calling `isPointInPolygon` multiple times?

**Comment by arsonik** [comment]
would be actually really awesome to call `isPointInPolygon` with a geojson mulipolygon !

**Comment by GunnarAK** [comment]
@AnthonyMouallem What would be the benifit of this? Either the lib cycles through all polygons or you do..

Just write
```
let positivePolygonIds = [];

for(const polygon of allPolygonsArray) {
   if (isPointInPolygon(point, polygon)) {
      positivePolygonIds.push(polygon.id);
   }
}

if(positivePolygonIds.length > 0) {
   // point was found in at least one polygon
}

**Comment by manuelbieh** [comment]
As @GunnarAK said: either the library does it or you do. I see no sense in adding it to the library. It should be done in user land. You can use `Array.some` to iterate through your polygons.
