### ISSUE TITLE
JSDOC types can only be used inside documentation error

### ISSUE THREAD

**Issue by julian-okello** [manuelbieh/geolib#218]
File: geolib/es/types.d.ts
export declare type GeolibGeoJSONPoint = [GeolibLongitudeInputValue, GeolibLatitudeInputValue, GeolibAltitudeInputValue?];

throws error when building node application but when the typing is removed i.e the question mark, error is gone. Please fix this asap

**Comment by manuelbieh** [comment]
This should not happen anymore. Feel free to re-open if it does.
