### ISSUE TITLE
TypeError: geolib.wktToPolygon is not a function

### ISSUE THREAD

**Issue by jdang67** [manuelbieh/geolib#221]
Hi, 

I just downloaded the latest version of  geolib and try to convert a WKT text  and got this exception:

``` javascript
  const points = geolib.wktToPolygon('POLYGON ((30 10.54321, 40 40, 20 40, 10 20, 30 10))');
```
and got : TypeError: geolib.wktToPolygon is not a function

thanks,

Jdang

**Comment by phferraz** [comment]
same here...

**Comment by phferraz** [comment]
**This is a workaround.**

I've found a solution that worked for me. Depending on your setup this might be possible as well.

I simply convert in advance when query from the database. This way I avoid using wktToPolygon function.

`ST_AsGeoJSON(polygon) as polygon_geojson`

**Comment by manuelbieh** [comment]
Indeed. The export was missing. This is fixed in the next release
