### ISSUE TITLE
[FR] More conversion functions for calculating distances

### ISSUE THREAD

**Issue by michtio** [manuelbieh/geolib#224]
It would be nice to be able to also convert not just from meters to anything else, but also from lets say, miles to meters.

Currently I'm in a situation where we know the radius has to be 10 miles for the points, but I still need to calculate how much meters that is, manually or through another custom written function. 

It wouldn't harm to have a function like: 

`convertUnits( value, fromUnit, toUnit)`

**Comment by manuelbieh** [comment]
I'm pretty sure there's already anything between one and ~1700 libraries to do unit conversion on npm. `convertUnit` is only a convenience method to display results in other units than meter. Alternatively, I'm exporting all the values necessary to do the conversion manually:
https://github.com/manuelbieh/geolib/blob/master/src/constants.ts#L24

You could e.g. do:
```
import { distanceConversion } from 'geolib/es/constants';

const tenMilesInMeters = Math.floor(10000 / distanceConversion.mi) * distanceConversion.km
```
Maybe I should export them in the CommonJS build as well 🤔

**Comment by manuelbieh** [comment]
3.3.0 now exports `distanceConversion` from constants.ts

**Comment by pate313373** [comment]
I agree to the request of @michtio - I'm in the same situation.

As the philosophy of geolib is to have zero dependencies, I'd like to keep that. Now I'm forced to add another. :(

Nice lib anyway, thx @manuelbieh

**Comment by manuelbieh** [comment]
https://www.npmjs.com/package/convert-units

```sh
npm install convert-units --save
```
```js
const convert = require('convert-units');
const thousandThreehundredMilesInMeters = convert(1300).from('mi').to('m');
geolib.doWhatever(thousandThreehundredMilesInMeters);
```
