### ISSUE TITLE
ReferenceError: geolib is not defined 

### ISSUE THREAD

**Issue by bsebag** [manuelbieh/geolib#225]
Hello,
I'm trying to use geolib but right now I am making a very simple test. I'm gettgin the following error:

ReferenceError: geolib is not defined
    at Object.<anonymous> (/Users/benysebag/Desktop/VOLL_NACPRO/EATZAP/PIZZA_PRIME/delivery_solution/locationmethod.js:1:1)

The code is extremely simple. Just want to use the method: ispointinpolygon. Please check below:

const geolib = require('geolib');

var result = geolib.isPointInPolygon({ latitude: 51.5125, longitude: 7.485 }, [
  { latitude: 51.5, longitude: 7.4 },
  { latitude: 51.555, longitude: 7.4 },
  { latitude: 51.555, longitude: 7.625 },
  { latitude: 51.5125, longitude: 7.625 },
]);

console.log(result);

**Comment by manuelbieh** [comment]
Works for me. Maybe update your Node or Geolib version.
```
$ node
Welcome to Node.js v12.13.1.
Type ".help" for more information.
> var geolib = require('.')
undefined
> var result = geolib.isPointInPolygon({ latitude: 51.5125, longitude: 7.485 }, [
... { latitude: 51.5, longitude: 7.4 },
... { latitude: 51.555, longitude: 7.4 },
... { latitude: 51.555, longitude: 7.625 },
... { latitude: 51.5125, longitude: 7.625 },
... ]);
undefined
>
> console.log(result);
true
```
