### ISSUE TITLE
Question: is there a method that exists to create a random offset from a point?

### ISSUE THREAD

**Issue by devoNOTbevo** [manuelbieh/geolib#229]
I imagine geolib has capabilities to do this:

- create a circle of specific radius, the center of which is a provided point.
- randomly generate another point within that radius (somehow).

My use case was an application where easiest intake was for users to input an address.  Assuming they put in their home address, the resulting data visualization displayed exactly on their house.

For privacy reasons, I was thinking of simply randomizing my geopoints within a certain radius (let's say 100-300 feet).

Again, I am sure I can find a way to do this geometrically, but wanted to get some feedback here.  If this proves valuable, I'd be happy to contribute as well.

Thanks in advance.

**Comment by manuelbieh** [comment]
There's no such method yet and while reading the first few sentences of your issue I thought that this should probably not be done on library level but your usecase made me curious.

There is: [#computeDestinationPoint](https://github.com/manuelbieh/geolib#computedestinationpointpoint-distance-bearing-radius--earthradius)
```
computeDestinationPoint(point, distance, bearing, radius = earthRadius)
```

You could pretty easily build such a function by randomizing the distance and the bearing parameters.
