### ISSUE TITLE
How to Convert Address into Polygon(lat and lon form)

### ISSUE THREAD

**Issue by Sher7298** [manuelbieh/geolib#230]
Want to know that how to convert Point and am doing this for lat 27 days :(
(indices => loc[0].longitude, loc[0].latitude ) into Polygon(Indices => ???)

i tried this  for inner and outer ring but Got Error "Cannot read property 'longitude' of undefined"
when i convert address into pint ot work
 this.location = {
      geometry: {
        type: "Polygon",
        coordinates:
         [
          [ [loc[0][0].longitude, loc[0][1].latitude],
            [loc[1][0].longitude, loc[1][1].latitude],
            [loc[2][0].longitude, loc[2][1].latitude],
            [loc[3][0].longitude, loc[3][1].latitude],
            [loc[4][0].longitude, loc[4][1].latitude],
          ],
          [ [loc[0][0].longitude, loc[0][1].latitude],
            [loc[1][0].longitude, loc[1][1].latitude],
            [loc[2][0].longitude, loc[2][1].latitude],
            [loc[3][0].longitude, loc[3][1].latitude],
            [loc[4][0].longitude, loc[4][1].latitude],
          ]
        ]
      },

**Comment by manuelbieh** [comment]
If you get `Cannot read property 'longitude' of undefined"` make sure the objects you're working with are correct.
