### ISSUE TITLE
makePolygon(point, radius, precision) [feature-request]

### ISSUE THREAD

**Issue by brussee** [manuelbieh/geolib#240]
Hi,
Thanks for this helpful library!

Please add a function to create a polygon (circle) based on a given point and radius.
For precision I'd suggest the amount of points (n) on the circle as in n=2^x.
I think this is very close to and in line with what this library is already capable of.

Thanks again!

**Comment by brussee** [comment]
I've found this lib that covers my usecase nicely: https://github.com/gabzim/circle-to-polygon

**Comment by manuelbieh** [comment]
You could relatively easily build such a function by using `computeDestinationPoint`.

Untested example:

```js
const point = { latitude: 52.518611, longitude: 13.408056 };
const distance = 5000; // 5 kilometers radius
const circle = [];

for (let i = 0; i < 360; i+=10) {
  circle.push(computeDestinationPoint(point, distance, i));
}
```

![image](https://user-images.githubusercontent.com/239546/89640045-07cd6880-d8af-11ea-9827-dfab41caf409.png)

**Comment by brussee** [comment]
Looks good, thanks for the effort!

Does this also work properly around the poles and the date line? (I can it out myself.)
