### ISSUE TITLE
Does the getAreaOfPolygon function return the correct area in square meters ?

### ISSUE THREAD

**Issue by LNga** [manuelbieh/geolib#242]
Hi there !

I am trying to use the **getAreaOfPolygon** function using the 4 points(lat,lon) below : 

[48.97261153645164, 2.514805581142397]
[48.97113960723603, 2.513668647512595]
[48.97087902193817, 2.514655420096959]
[48.97237208681169, 2.5156314668923456]

I am getting 19904.36 m² as an answer, while I am supposed to find around 15 000 m².

Does someone find 15 000 m² (approximately) with the given points ?

Thanks for your help.

**Comment by manuelbieh** [comment]
Oh, that would mean the whole formula/function to calculate the area is wrong. I will verify that!

**Comment by manuelbieh** [comment]
Hmm you sure it should be around 15 sqkm? I checked your coordinates using [turf/area](https://www.npmjs.com/package/@turf/area) and it has the exact same results as Geolib's `getAreaOfPolygon` function.
