### ISSUE TITLE
isPointWithinRadius returns false even if true

### ISSUE THREAD

**Issue by patrickpoon-ucberkeley** [manuelbieh/geolib#247]
When calling `isPointWithinRadius()` with the following GPS coordinates and a radius of 10 [meters], it returns false, even though the actual distance is 9.51 meters as calculated by calling `getDistance()`:
Point 1: { latitude: 42.53098, longitude: -71.28029 }
Point 2: { latitude: 42.53101, longitude: -71.2803986 }

`isPointWithinRadius()` calls `getDistance()` without an accuracy value, so it appears to round up the comparison, which ends up being 10 < 10 = false instead of 9.51 < 10 = true.

**Comment by kalleriakronos24** [comment]
+1 
same issue here

**Comment by manuelbieh** [comment]
Good find!

**Comment by kuromadara** [comment]
were you able to solve this I also get false for isPointWithinPolygon

var tf = geolib.isPointInPolygon({ latitude: {lat: location.latitude}, longitude: {lng: location.longitude} }, [
    { latitude: 27.483871, longitude:  95.204824},
    { latitude: 27.484353, longitude: 95.195472},
    { latitude: 27.492926, longitude: 95.4932795 },
    { latitude: 27.492956, longitude: 95.177179 },

  ]);

tf is false however its true if i hardcode the points within the bound

**Comment by ferasallaou** [comment]
I'm still facing the same issue with version 3.3.4, I hard coded the coordinates, and can still see the same issue

**Comment by abdi4** [comment]
@ferasallaou i'm facing the same issue. did you manage to solve it?
