### ISSUE TITLE
getDistance / getPreciseDistance returning NaN for all sets of coordinates

### ISSUE THREAD

**Issue by EloiSir** [manuelbieh/geolib#256]
Hello,

I am using geolib@3.3.1, and getDistance and getPreciseDistance both return NaN for any set of coordinates I've tried. I ran npm install geolib. 

What could be the reason for this problem?

Thanks in advance.

**Comment by manuelbieh** [comment]
Do you have an example? The correct syntax for both is `getDistance(start, end)` where `start` and `end` both must be a [GeolibInputCoordinate](https://github.com/manuelbieh/geolib/blob/master/src/types.ts#L34)
