### ISSUE TITLE
getCenter fn examples not working

### ISSUE THREAD

**Issue by trinityXmontoya** [manuelbieh/Geolib#41]
I am using geolib in a project. The getCenter() fn was not working, I followed the source code and was unable to determine why. I then tried running the basic examples from the README in the Chrome console and these returned the same errors I was receiving.

```
 var spots = {
    "Brandenburg Gate, Berlin": {latitude: 52.516272, longitude: 13.377722},
    "Dortmund U-Tower": {latitude: 51.515, longitude: 7.453619},
    "London Eye": {latitude: 51.503333, longitude: -0.119722},
    "Kremlin, Moscow": {latitude: 55.751667, longitude: 37.617778},
    "Eiffel Tower, Paris": {latitude: 48.8583, longitude: 2.2945},
    "Riksdag building, Stockholm": {latitude: 59.3275, longitude: 18.0675},
    "Royal Palace, Oslo": {latitude: 59.916911, longitude: 10.727567}
}

geolib.getCenter(spots);
```
 **returns "false"**

```
geolib.getCenter([
    {latitude: 52.516272, longitude: 13.377722}, 
    {latitude: 51.515, longitude: 7.453619}, 
    {latitude: 51.503333, longitude: -0.119722}
])
```
**throws error  Uncaught TypeError: Cannot read property 'latitude' of undefined**

**Comment by manuelbieh** [comment]
The first one doesn't work because `geolib.getCenter` expects an array. The second example works for me in Firefox, Chrome and Internet Explorer (11).
```
var spots = [
    {latitude: 52.516272, longitude: 13.377722},
    {latitude: 51.515, longitude: 7.453619},
    {latitude: 51.503333, longitude: -0.119722},
    {latitude: 55.751667, longitude: 37.617778},
    {latitude: 48.8583, longitude: 2.2945},
    {latitude: 59.3275, longitude: 18.0675},
    {latitude: 59.916911, longitude: 10.727567}
]
geolib.getCenter(spots);
>> Object {latitude: "54.387605", longitude: "18.749028", distance: 2693.471}

geolib.getCenter([
    {latitude: 52.516272, longitude: 13.377722}, 
    {latitude: 51.515, longitude: 7.453619}, 
    {latitude: 51.503333, longitude: -0.119722}
])
>> Object {latitude: "52.009802", longitude: "6.629000", distance: 932.209}
```

**Comment by trinityXmontoya** [comment]
Yes you are right! I was referencing the wrong branch in my code, thank you for taking the time to look at this.

And the first example is from the README and shows it as an object not an array.

**Comment by ngprnk** [comment]
This will work 

class Distance {
  toRadians(degrees) {
    return degrees * (Math.PI / 180);
  }

  calc(from, to) {
    const lat1 = parseFloat(from.lat);
    const lon1 = parseFloat(from.lng);
    const lat2 = parseFloat(to.lat);
    const lon2 = parseFloat(to.lng);
    const R = 6371; // Radius of the earth in km
    const dLat = this.deg2rad(lat2 - lat1); // deg2rad below
    const dLon = this.deg2rad(lon2 - lon1);
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(this.deg2rad(lat1)) * Math.cos(this.deg2rad(lat2)) *
      Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    const d = R * c; // Distance in km
    return d;
  }

  deg2rad(deg) {
    return deg * (Math.PI / 180);
  }
}

export default new Distance();
