### ISSUE TITLE
Documentation - lng lat order

### ISSUE THREAD

**Issue by ozomer** [manuelbieh/Geolib#44]
From the README.md:

> Works with:
> - latitude: `latitude`, `lat`, 0 (GeoJSON array)
> - longitude: `longitude`, `lng`, `lon`, 1 (GeoJSON array)

When these functions are called with an array *longitude* returns the first element and *latitude* returns the second element.

**Comment by manuelbieh** [comment]
Whooops!

Fixed it, thank you!
