### ISSUE TITLE
request: travel a distance

### ISSUE THREAD

**Issue by kevinburkeshyp** [manuelbieh/Geolib#45]
Say I wanted to get, roughly, a 30km by 30km square around a given lat/long, how would I do this?

Something like `geolib.travel(lat, long, 30, 'km', degrees)` where degrees is a number between 0 and 359.9999, and indicates the direction of travel..

**Comment by manuelbieh** [comment]
Good idea!

**Comment by manuelbieh** [comment]
http://www.movable-type.co.uk/scripts/latlong.html#destPoint

**Comment by manuelbieh** [comment]
http://www.geomidpoint.com/destination/

Some nice sources to get some inspiration from ;)

**Comment by manuelbieh** [comment]
Short update: we now have a half finished pull request which implements the movable-type function I mentioned above: #66

**Comment by ath88** [comment]
So, I assume this is still open, because you requested some unit tests in #66?

**Comment by manuelbieh** [comment]
Nope. This one is still open because I just forgot to close it ;) The PR was merged and tests were added!
