### ISSUE TITLE
about keyword 'this'

### ISSUE THREAD

**Issue by CoderIvan** [manuelbieh/Geolib#46]
var geolib = require('geolib');

geolib.getDistance(
	{latitude: 51.5103, longitude: 7.49347},
	{latitude: "51° 31' N", longitude: "7° 28' E"}
);

// when
var warper = geolib.getDistance
warper(
	{latitude: 51.5103, longitude: 7.49347},
	{latitude: "51° 31' N", longitude: "7° 28' E"}
);

// throw

// TypeError: Cannot read property 'coords' of undefined
//     at geolib.extend.getDistance (*\geolib\node_modules\geolib\dist\geolib.js:229:16)
//     at Object.<anonymous> (*\geolib\test.js:10:1)
//     at Module._compile (module.js:460:26)
//     at Object.Module._extensions..js (module.js:478:10)
//     at Module.load (module.js:355:32)
//     at Function.Module._load (module.js:310:12)
//     at Function.Module.runMain (module.js:501:10)
//     at startup (node.js:129:16)
//     at node.js:814:3

**Comment by CoderIvan** [comment]
maybe 

geolib.prototype[prop] = typeof methods[prop] === 'function' ? methods[prop].bind(this) : methods[prop];

is better?

**Comment by manuelbieh** [comment]
... or you could use `var warper = geolib.getDistance.bind(geolib);` instead as a quick workaround.

Your way is definitely the better one. Thanks! 

I will change it in the lib soon but currently all unittests fail in node.js when changing:
`geolib.prototype[prop] = methods[prop];`
to:
`this.prototype[prop] = typeof methods[prop] === 'function' ? methods[prop].bind(this) : methods[prop];`

and I have yet no idea why.

**Comment by CoderIvan** [comment]
thank you for your reply.
