### ISSUE TITLE
isPointInside

### ISSUE THREAD

**Issue by CoderIvan** [manuelbieh/Geolib#47]
var geolib = require('geolib');

var polygon = [
    {latitude: -46, longitude: 1},
    {latitude: -46, longitude: 2},
    {latitude: -47, longitude: 2},
    {latitude: -47, longitude: 1}
];
console.log(geolib.isPointInside({ latitude:-46, longitude:1}, polygon)) // --> false
console.log(geolib.isPointInside({ latitude:-46, longitude:2}, polygon)) // --> false
console.log(geolib.isPointInside({ latitude:-47, longitude:2}, polygon)) // --> false
console.log(geolib.isPointInside({ latitude:-47, longitude:1}, polygon)) // --> true

why get different result?

**Comment by manuelbieh** [comment]
That is a legitimate question. I copied the algorithm from somewhere I can't remember. Seems to be buggy. I have just found this one:
https://github.com/substack/point-in-polygon/blob/master/index.js

I think I will have a look if this one works better shortly.

**Comment by manuelbieh** [comment]
Ok, seems to have the same issue ;)
https://github.com/substack/point-in-polygon/issues/2

So this one seems to be better:
https://github.com/mikolalysenko/robust-point-in-polygon
(holy crap, what a code!)

**Comment by deepaksisodiya** [comment]
hi...should I use this npm library or not, seems to be bug in isPointInside method?

**Comment by manuelbieh** [comment]
Depends on what you need. If you need a 100% accurate function to check whether a point is inside of a polygon or not, don't use it (yet). For everything else: sure, use it!

**Comment by deepaksisodiya** [comment]
thanks @manuelbieh

**Comment by manuelbieh** [comment]
I experimentally implemented the great [robust-point-in-polygon](https://github.com/mikolalysenko/robust-point-in-polygon) function from @mikolalysenko - you can use it like this:

```
var geolib = require('./dist/geolib.isPointInsideRobust')(require('geolib'));

var polygon = [
  {latitude: -46, longitude: 1},
  {latitude: -46, longitude: 2},
  {latitude: -47, longitude: 2},
  {latitude: -47, longitude: 1}
];

console.log(geolib.isPointInsideRobust({ latitude:-46, longitude:1}, polygon)) // --> 0
console.log(geolib.isPointInsideRobust({ latitude:-46, longitude:2}, polygon)) // --> 0
console.log(geolib.isPointInsideRobust({ latitude:-47, longitude:2}, polygon)) // --> 0
console.log(geolib.isPointInsideRobust({ latitude:-47, longitude:1}, polygon)) // --> 0
```

where `0` means the point is directly on the boundaries (then it's up to you whether you count it as "inside" or not), `-1` means it is inside the given polygon and `1` means it is outside of the polygon.

In the browser just load the `geolib.isPointInsideRobust.js` after you loaded geolib.js. Then you can use `geolib.isPointInsideRobust()`:

```
<script src="dist/geolib.js"></script>
<script src="dist/geolib.isPointInsideRobust.js"></script>
<script>
// use geolib.isPointInsideRobust() here
</script>
```
