### ISSUE TITLE
getCenter() returns distance in km, not meters

### ISSUE THREAD

**Issue by ivanakimov** [manuelbieh/Geolib#48]
You have distance as meters everywhere in your documentation, but `getCenter` returns kilometers.
`geolib@2.0.14`

**Comment by manuelbieh** [comment]
Do you really need the distance at all? It was dropped completely in 2.0.15. I should remove it from the docs, unless you tell me that you need this value (and what you need it for :wink: ).

**Comment by ivanakimov** [comment]
I'm using this function for store locator software to calculate the distance between users and stores. It seems like basic geo calculation that a geo library should support, what were the reasons for dropping it?

**Comment by manuelbieh** [comment]
That's what ``geolib.getDistance(src, dest)`` is meant for. 

``geolib.getCenter(poly)`` is just to give you the center point of a polygon.

**Comment by manuelbieh** [comment]
Example:
``var distanceFromUserToStore = geolib.getDistance(userPosition, storePosition);``
