### ISSUE TITLE
Sub-meter accuracy in getDistance?

### ISSUE THREAD

**Issue by tengyifei** [manuelbieh/geolib#51]
Is there a way to achieve sub-meter accuracy? I'm pretty sure the raw distance has more resolution than meters before rounding. Thanks!

**Comment by andresn** [comment]
:+1:

**Comment by manuelbieh** [comment]
This should be possible in v3.0.0 by using 0.01 (cm) or 0.001 (mm) as third parameter to `getDistance`. Will be released shortly.
