### ISSUE TITLE
Using the Coordinates object from the geolocation API causes an error

### ISSUE THREAD

**Issue by bregnvig** [manuelbieh/geolib#56]
It would be nice if it was possible to use the Coordinates object returned by the geolocation API.

But since the getKey function has this requirement:

```
return point.hasOwnProperty(val) ? (function() { key = val; return false; }()) : true;
```

And the Coordinates latitude & longitude is in the prototype, I get:

```
Cannot read property 'latitude' of undefined 
```

When trying to calculate a distance. 

Currently I'm just using:

```
{
   'latitude':position.coords.latitude,
   'longitude':position.coords.longitude
};
```

But it would just be nicer if I could use the object as it were. Anyways - great library. Thanks

**Comment by nitindhar7** [comment]
Yep, would be good to follow the [GeoJSON spec](http://geojson.org/). Structure would look like:

```javascript
{
    type: "Point",
    coordinates: [40, -73] // [longitude, latitude]
}
```

Most GIS tools ([MongoLab/MongoDB](http://blog.mlab.com/2014/08/a-primer-on-geospatial-data-and-mongodb/), [Mapbox](https://www.mapbox.com/)) follow the GeoJSON spec and so data flows between them seamlessly!

**Comment by manuelbieh** [comment]
Hi. I'm currently working on Geolib 3 which supports custom Coordinate types. Maybe I will include a GeoJSON Coordinate type by default. We'll see ;)

**Comment by nitindhar7** [comment]
@manuelbieh let me know if you need help with it. I'm currently working on a geolocation based system and am interested in your library. Would be willing to help iron kinks out. Is there some place I can see the geolib3 api or what you're thinking of doing?

**Comment by manuelbieh** [comment]
This should no longer happen. Re-open if it still does!
