### ISSUE TITLE
Document undocumented functions

### ISSUE THREAD

**Issue by stefanvangastel** [manuelbieh/geolib#59]
Hi,

I was looking for a js geo library that could also calc bearing and direction. At first your (great!) lib didn't seem to do that until I took a closer look at the example page. Seems it can indeed do so as I also found in the src file (getRhumbLineBearing, getBearing, getDirection, etc).

I would recommend documenting this so even more people will be finding a great solution in your lib!

**Comment by chucre** [comment]
This was added in PR #68

**Comment by anuragagarwal561994** [comment]
Hi, I have submitted a PR #96 for the same.
I would like to help in finishing the undocumented methods of this library.
