### ISSUE TITLE
Heading between 2 sets of coordinates

### ISSUE THREAD

**Issue by ghost** [manuelbieh/geolib#60]
Feature request to add the calculation of the straight line bearing between two points/coordinates.

**Comment by nkolban** [comment]
+1 on this request.  What help is needed?

**Comment by ath88** [comment]
Does this await a PR? Or what kind of help is needed?

**Comment by manuelbieh** [comment]
What we already have is this (yet undocumented(?!)) function:
https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L825

This should be it, I guess?
