### ISSUE TITLE
hasOwnProperty in getKeys causing undefined values

### ISSUE THREAD

**Issue by chadwilson** [manuelbieh/geolib#62]
On line 110 of geolib.js the lookup of the latitude, longitude and elevation fields on the point object is currently the following:

return point.hasOwnProperty(val) ? (function() { key = val; return false; }()) : true;

The issue I'm seeing is for some object that are created by frameworks (loopback for instance), the fields are set on the prototype and not the object itself.  hasOwnProperty does not check the prototype values, and as such I'm seeing undefined exceptions being thrown when the json debugging output looks fine.

I have done a local test and changed the line to the following:

return val in point ? (function() { key = val; return false; }()) : true;

The in keyword returns the proper fields and everything works as expected.

**Comment by chadwilson** [comment]
Included a pull request https://github.com/manuelbieh/Geolib/pull/63

**Comment by manuelbieh** [comment]
https://github.com/manuelbieh/Geolib/pull/63#commitcomment-14955446
