### ISSUE TITLE
getCenter should convert coords if passed as array

### ISSUE THREAD

**Issue by ozomer** [manuelbieh/geolib#70]
`getDistance` begins with:

```
var s = this.coords(start);
var e = this.coords(end);
```

so if the coordinates are passed as `[lng, lat]` pairs, they will be converted.

Why not doing the same for `getCenter`? It should also begin with:

```
coords = coords.map(this.coords);
```

P.S. The `[lng, lat]` form is much more common among those who use GeoJson.

**Comment by ozomer** [comment]
The geolib package is great, but it should be wrapped by a new package for those who want to use GeoJson format in all inputs and outputs (use `[lng, lat]` syntax, or even `{"type":"Point","coordinates":[lng,lat]}`).

I see that the name `geojsonlib` is available.
Anyone wants to take the challenge?

**Comment by manuelbieh** [comment]
This should have been fixed already. If not, it definitely is in v3.0.0 which I will release shortly!
