### ISSUE TITLE
Area of a polygon (and multi-polygon)

### ISSUE THREAD

**Issue by FiddlinBill** [manuelbieh/geolib#71]
It would be great if there was a method for calculating the area of a polygon.

**Comment by gauthampait** [comment]
This is a really important feature. Any suggestion where to start from ? I can probably do a bit of research and contribute.

**Comment by FiddlinBill** [comment]
I know ArcGIS has solved this problem [before](https://github.com/Esri/arcgis-js-api).

**Comment by gauthampait** [comment]
Any idea where ? Is there a Util class that I can use ? Been looking for a solution for months now. Any help would be really appreciated.

**Comment by manuelbieh** [comment]
Sorry for not responding so long. There is a new method `getAreaOfPolygon` that will be added to v3.0.0 which I will release shortly! Thanks for the idea!
