### ISSUE TITLE
Calculate distance beetween point and line

### ISSUE THREAD

**Issue by Lev-Zabudko** [manuelbieh/Geolib#72]
It would be great if we had something like that:
distanceToLine(point, lineStart, lineEnd)  //returns distance in meters to nearest point of the line.

BTW thx for your GeoLib!!!

**Comment by aindeev** [comment]
+1 I am also looking for something like this! @Lev-Zabudko have to found any other library of snippet somewhere that would do this. Struggling with the math myself :smile:

**Comment by Lev-Zabudko** [comment]
@aindeev nope. I was needed it just for testing some app logic. Now my code divides line for 9 lines and searching for the nearest start/end of that lines =) That workaround loads cpu, but it's not so important now with my data.
At production it works with MongoDB, that could find objects we need:
https://docs.mongodb.org/manual/reference/operator/query/near/

**Comment by maximepeabody** [comment]
Hello, I am working on this right now. If we take point, lineStart and lineEnd, we can create a triangle and use trigonometry to find the minimum distance from the point to the line.

**Comment by Lev-Zabudko** [comment]
wow, seems it's in default now.
Thanks @maximepeabody for [#76 pull request](https://github.com/manuelbieh/Geolib/pull/76)
