### ISSUE TITLE
Latitude Longitude set to geoJSON

### ISSUE THREAD

**Issue by m-menon** [manuelbieh/geolib#81]
hi,

Just stumbled on this and think that it could be pretty useful in one of my projects. But just curious whether it is possible to convert a set of latitude, longitude json to geoJSON format. This is because I already have it saved in decimal degress but one of the map update methods actually works only with GeoJSON. Thanks for the great work. Cheers - M.M

**Comment by manuelbieh** [comment]
It's currently not possible to convert lat/lng coordinates into GeoJSON format but that's also not really necessary as geolib works with both formats. Maybe a converter would be a nice addition for v3. I will keep that in mind.
