### ISSUE TITLE
Update computeDestinationPoint documentation

### ISSUE THREAD

**Issue by Ryandev** [manuelbieh/geolib#83]
1. README.md refers to computeDestinationPoint accepting latitude and longitude as seperate arguments however the function accepts both as a single argument.
2. Inside geolib.js for computeDestinationPoint the comment header doesn't match up to the function either. As it references longitude as a separate argument again.
3. computeDestinationPoint comment header refers to argument earth radius which doesn't exist

**Comment by tab00** [comment]
I ran into a problem due to incorrect documentation as described above.

**Comment by manuelbieh** [comment]
I'm sorry for that! I will have a look at it when I will write the docs for the upcoming v3 release.

**Comment by manuelbieh** [comment]
Ok, clarified the docs. Will be published once the v3 branch was merged into master.
