### ISSUE TITLE
precision in geolib.getDistance not taken into account

### ISSUE THREAD

**Issue by sylvainlap** [manuelbieh/geolib#90]
Hi,

I want to get distance between 2 points with a centimeter precision. So I call:

```
geolib.getDistance({
  longitude: 1.4191279,
  latitude: 43.597496,
}, {
  longitude: 9.1981302,
  latitude: 45.4813073,
}, 1, 3);
```

but whatever the precision, I always get a meter precision. Is that last parameter really taken into account ?

**Comment by sylvainlap** [comment]
I looked at the code, and the problem is here:
https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L358

Whatever the precision, it is reset by `Math.round(distance / accuracy)`. There's definitely something wrong there.

**Comment by sylvainlap** [comment]
I made this PR: https://github.com/manuelbieh/Geolib/pull/91

**Comment by Suven** [comment]
@manuelbieh Since the PR was merged and fixes a (imho) critical bug, it would be great to tag a new version.

The most recent version (2.0.21) does not include that fix yet.

**Comment by ken107** [comment]
I was kind of confused by these two options.  If I set accuracy to 100m, then would I care about sub-meter precision?  Similary if I want sub-meter precision, what would I set accuracy to?

Ultimately, I think the framework, which is concerned with calculation, should always return its most accurate value.  The accuracy and precision are a matter of presentation.

**Comment by radvansky-tomas** [comment]
Any update here ?

**Comment by manuelbieh** [comment]
Precision will be dropped in v3.0.0. getDistance() now always returns precision on a meter level (and can be set to picometers if you want).
