### ISSUE TITLE
es6 support - import not working

### ISSUE THREAD

**Issue by exilonX** [manuelbieh/Geolib#93]
I tried to import geolib in an es6 project and I didn't succeed. I tried the following: 

1. import * as geolib1 from "geolib";
2. import geolib2 from "geolib";
3. import {geolib3} from "geolib";

geolib1 - { default: Geolib {} }
geolib2 - Geolib {}
geolib3 - undefined

I think that the first version should work.

**Comment by manuelbieh** [comment]
The second version is right. Geolib does not have multiple exports so `import * ...` is "wrong". Just try `import geolib from "geolib"` and then `geolib.getDistance(...)` should work as expected.

**Comment by exilonX** [comment]
It worked. Thanks.

**Comment by arodr967** [comment]
I think it would be helpful to add the import statement on your readme, I was trying to look on how to do it as well.
Thanks!
