### ISSUE TITLE
new Feature

### ISSUE THREAD

**Issue by didix16** [manuelbieh/geolib#98]
Hi! First of all, thanks for this awesome lib!
Well in my project I want to make  a route by connecting all the points.
So I'm wondering if is possible to add a feature like 'genOptimeRoute' that passing the current position and an array of LatLng objects, generates a route, making a path from node1 (origin) to node2, node2 to node3, etc...

Thanks in advance :)

**Comment by manuelbieh** [comment]
What you're talking about sounds like the [Travelling Salesman Problem](https://en.wikipedia.org/wiki/Travelling_salesman_problem) which is far away from being trivial. You could probably write a whole library for that problem alone. So to answer your question: highly unlikely that such a function will be part of Geolib one day (although that would be pretty awesome :wink: )

**Comment by didix16** [comment]
Oh well... Anyway thanks for the info. I'll search info about TSP :). If is so harder, I hope one day could write a method for geolib using TSP :D 
Thank you so much

**Comment by manuelbieh** [comment]
http://parano.github.io/GeneticAlgorithm-TSP/

**Comment by manuelbieh** [comment]
This one might help: http://parano.github.io/GeneticAlgorithm-TSP/

**Comment by didix16** [comment]
Whoa it seems very interesting! I'll try to understand it for adapt it to my project. Thank you :D
